apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gadget4-beta

resources:
  - ../../base/api
  - ../../base/workers
  - ../../base/redis
  - ../../base/postgres
  - namespace.yaml

images:
  - name: gcr.io/gadget-479011/gadget4-api
    newTag: beta-latest
  - name: gcr.io/gadget-479011/gadget4-worker
    newTag: beta-latest

commonLabels:
  environment: beta

patches:
  - path: patches/api-replicas.yaml
  - path: patches/worker-replicas.yaml
  - path: patches/environment.yaml
